apiVersion: v1
kind: Service
metadata:
  name: px-central-svc
  label: 
    app: px-central
  namespace: portworx-system
spec:
  type: LoadBalancer
    selector:
      app: mypostgres
      replicationRole: primary
    ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432