apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - image: janpipan/djangodatabase:1.0
        name: django
        command: ['/bin/bash', 'run.sh']
        ports:
        - containerPort: 8000
          name: gunicorn
        volumeMounts:
          - name: settings
            mountPath: /app/djangodatabase/settings.py
            subPath: settings.py
      volumes:
      - name: settings
        configMap:
          name: django-config
          items:
            - key: settings
              path: settings.py
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        tolerationSeconds: 10
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        tolerationSeconds: 10
      